# Generated by Django 3.2.6 on 2021-09-07 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210906_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dp',
            field=models.ImageField(blank=True, default='profiles/download_1.jpeg', null=True, upload_to='profiles/'),
        ),
    ]
