# Generated by Django 3.2.6 on 2021-09-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_dp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coverimage',
            field=models.ImageField(blank=True, default='covers/images.png', null=True, upload_to='covers/'),
        ),
    ]
