# Generated by Django 3.2.6 on 2021-08-31 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('tools_used', models.CharField(choices=[('PHOTOSHOP', 'ADOBE PHOTOSHOP'), ('ILLUSTRATE', 'ADOBE ILLUSTRATE'), ('AEFFECTS', 'ADOBE AFTER EFFECTS'), ('PREMIEREPRO', 'ADOBE PREMIERE PRO')], max_length=200)),
                ('Cover', models.ImageField(upload_to='media')),
                ('tags', models.ManyToManyField(blank=True, to='work.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.TextField()),
                ('coment_date', models.DateTimeField(auto_now_add=True)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.work')),
            ],
        ),
        migrations.CreateModel(
            name='Appreciate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.work')),
            ],
        ),
    ]
