# Generated by Django 3.2.6 on 2021-09-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='work',
            name='tools_used',
        ),
        migrations.AddField(
            model_name='work',
            name='tools_used',
            field=models.ManyToManyField(blank=True, null=True, to='work.Tools'),
        ),
    ]
