# Generated by Django 3.2.6 on 2021-09-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20210901_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='tools_used',
            field=models.ManyToManyField(blank=True, to='work.Tools'),
        ),
    ]
