# Generated by Django 3.2.6 on 2021-09-01 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('work', '0003_alter_work_tools_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
    ]
