# Generated by Django 3.2.6 on 2021-09-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_comment_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
