# Generated by Django 3.2.6 on 2021-09-07 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210906_1359'),
        ('work', '0006_auto_20210904_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='appreciate',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
