# Generated by Django 3.2.6 on 2021-09-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_appreciate_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='work',
            name='imageone',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
