# Generated by Django 3.2.6 on 2021-09-07 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_auto_20210907_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='image2',
            new_name='imagetwo',
        ),
    ]
